# Generated by Django 5.1.5 on 2025-04-20 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fituser',
            old_name='AdditionalNotes',
            new_name='Additional_Notes',
        ),
        migrations.RenameField(
            model_name='fituser',
            old_name='LifestyleHabits',
            new_name='Lifestyle_Habits',
        ),
        migrations.AlterField(
            model_name='fituser',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fituser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.RemoveField(
            model_name='fituser',
            name='friends',
        ),
        migrations.AlterField(
            model_name='fituser',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fituser',
            name='friends',
            field=models.TextField(blank=True),
        ),
    ]
