# Generated by Django 5.1.5 on 2025-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fituser',
            name='Additional_Notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fituser',
            name='Lifestyle_Habits',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
