# Generated by Django 5.1.5 on 2025-04-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='exerciseassignment',
            name='duration_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exerciseassignment',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseassignment',
            name='fitpoint_reward',
            field=models.IntegerField(default=5),
        ),
    ]
