# Generated by Django 5.1.5 on 2025-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_muscle_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(max_length=1000),
        ),
    ]
